"""Plan data structures for the orchestrator."""

from dataclasses import dataclass, field
from enum import Enum


class StepStatus(Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class PlanStep:
    """A single step in an action plan."""

    index: int
    action: str  # tap, type, swipe, scroll, long_press, navigate_home, navigate_back, wait
    target_description: str
    target_index: int | None = None  # Jeeves element index (matches overlay numbers)
    input_text: str | None = None
    direction: str | None = None  # up, down, left, right
    expected_result: str = ""
    status: StepStatus = StepStatus.PENDING

    def mark_completed(self) -> None:
        self.status = StepStatus.COMPLETED

    def mark_failed(self) -> None:
        self.status = StepStatus.FAILED


@dataclass
class Plan:
    """A multi-step plan generated by the big model."""

    goal: str
    steps: list[PlanStep]
    success_indicator: str
    parse_error: bool = False
    current_step_index: int = 0
    _completed: bool = False

    @property
    def current_step(self) -> PlanStep | None:
        if self.current_step_index < len(self.steps):
            return self.steps[self.current_step_index]
        return None

    @property
    def is_complete(self) -> bool:
        return self._completed or self.current_step_index >= len(self.steps)

    @property
    def progress(self) -> float:
        if not self.steps:
            return 1.0
        return self.current_step_index / len(self.steps)

    def advance(self) -> PlanStep | None:
        """Mark current step complete and move to next. Returns new current step."""
        if self.current_step:
            self.current_step.mark_completed()
        self.current_step_index += 1
        return self.current_step

    def mark_complete(self) -> None:
        """Mark the entire plan as complete."""
        self._completed = True
        for step in self.steps:
            if step.status == StepStatus.PENDING:
                step.status = StepStatus.SKIPPED

    def to_dict(self) -> dict:
        """Convert plan to dictionary for logging/serialization."""
        return {
            "goal": self.goal,
            "success_indicator": self.success_indicator,
            "current_step": self.current_step_index,
            "total_steps": len(self.steps),
            "is_complete": self.is_complete,
            "steps": [
                {
                    "index": s.index,
                    "action": s.action,
                    "target": s.target_description,
                    "status": s.status.value,
                }
                for s in self.steps
            ],
        }
